data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://raw.githubusercontent.com/uiuc-cse/data-fa14/gh-pages/data/iris.csv
  local_data_file: artifacts/data_ingestion/iris.csv

data_validation:
  root_dir: artifacts/data_validation
  STATUS_FILE: artifacts/data_validation/status.txt
  local_data_file: artifacts/data_ingestion/iris.csv

